server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  port: 8080
  servlet:
    context-path: /school

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      username: root
      password: xx1602614lpc
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sys?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
  thymeleaf:
    mode: HTML5
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    static-path-pattern: /static/**
#  neo4j:
#    security:
#      hostname-verification-enabled:
#
logging:
  config: classpath:log4j2.yml
  level:
    com.example.springbootdemo1.mapper: debug

pagehelper:
  helperDialect: mysql
  reasonable: true
  params: count=countSql
  support-methods-arguments: true

mybatis-plus:
  mapper-locations: classpath:/mapping/*Mapper.xml
  type-aliases-package: com.lpc.springbootdemo1.model
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



