-- auto Generated on 2022-05-16
-- DROP TABLE IF EXISTS archive;
CREATE TABLE archive(
	user_id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT '用户Id',
	sex INT (11) NOT NULL DEFAULT -1 COMMENT '性别',
	age INT (11) NOT NULL DEFAULT -1 COMMENT '年龄',
	politic INT (11) NOT NULL DEFAULT -1 COMMENT '政治面貌',
	nation VARCHAR (50) NOT NULL DEFAULT '' COMMENT '籍贯',
	remark VARCHAR (50) NOT NULL DEFAULT '' COMMENT '备注',
	PRIMARY KEY (user_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'archive';
