-- auto Generated on 2022-05-14
-- DROP TABLE IF EXISTS dict;
CREATE TABLE dict(
	id INT (11) NOT NULL AUTO_INCREMENT COMMENT 'id',
	`name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '字典名称',
	type_code VARCHAR (50) NOT NULL DEFAULT '' COMMENT '类型代码',
	`value` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '字典值',
	order_num INT (11) NOT NULL DEFAULT -1 COMMENT '排序代码',
	remark VARCHAR (50) NOT NULL DEFAULT '' COMMENT '备注',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'dict';
