-- auto Generated on 2022-05-14
-- DROP TABLE IF EXISTS menu;
CREATE TABLE menu(
	id INT (11) NOT NULL AUTO_INCREMENT COMMENT '菜单id',
	p_id INT (11) NOT NULL DEFAULT -1 COMMENT '父级id',
	title VARCHAR (50) NOT NULL DEFAULT '' COMMENT '菜单名称',
	href VARCHAR (50) NOT NULL DEFAULT '' COMMENT '地址',
	icon VARCHAR (50) NOT NULL DEFAULT '' COMMENT '图标',
	`type` INT (11) NOT NULL DEFAULT -1 COMMENT '菜单类型',
	order_num INT (11) NOT NULL DEFAULT -1 COMMENT '排序代码',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'menu';

