-- auto Generated on 2022-05-14
-- DROP TABLE IF EXISTS role_user;
CREATE TABLE role_user(
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT 'id',
	user_id BIGINT (15) NOT NULL DEFAULT -1 COMMENT '用户id',
	role_i_d INT (11) NOT NULL DEFAULT -1 COMMENT '角色id',
	remark VARCHAR (50) NOT NULL DEFAULT '' COMMENT '备注',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'role_user';
