-- auto Generated on 2022-05-14
-- DROP TABLE IF EXISTS `role`;
CREATE TABLE `role`(
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT 'id',
	`name` VARCHAR (50) NOT NULL DEFAULT '' COMMENT '角色名',
	remark VARCHAR (255) NOT NULL DEFAULT '' COMMENT '备注',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '角色信息表';
